### ISSUE TITLE
New front-end: Grayjay for YouTube

### ISSUE THREAD

**Issue by PhilC813** [duyfken/alternative-front-ends#2]
### What platform does this front-end run on?

Mobile (Android/iOS)

### Front-end Name

Grayjay

### Front-end For

YouTube

### Front-end Repository

https://gitlab.futo.org/videostreaming/grayjay

### Main/Official Instance

https://grayjay.app/

**Comment by duyfken** [comment]
Added with https://github.com/duyfken/alternative-front-ends/commit/fd10c9eaa92dfc2bad8694a7fdb0821de9146bd4.

It has been added as a multi-service front-end, as in addition to Youtube, [Grayjay](https://github.com/futo-org/grayjay-android) also supports Kick, Rumble, Bitchute, Odysee, Patreon, Twitch, Spotify, Dailymotion, SoundCloud, Nebula, BiliBili and PeerTube.

I have also chosen to mention their Github (mirror) repository as their main repository as it appears to provide all the public issue tracking for this project.

**Comment by PhilC813** [comment]
Very good point about the multiple services. And thank you for adding it!

P.S., very nice fork of the other repo. The different branches between mobile/desktop/etc really help.

**Comment by PhilC813** [comment]
I'm not sure if there's a better way to implement it, but someone who is looking for a frontend for a specific service will most likely overlook the multi-service section. One thing you could consider is adding a shortcut in each relevant service, like such:
- Grayjay (see multi-service apps)

Or simply adding a hyperlink to the relevant service if there are URL anchors (e.g., [repo URL]#grayjay)

Especially when, with times, there will be more multi-services apps, they will become harder to surface (for the people who don't naturally use Ctrl+F)

**Comment by duyfken** [comment]
When I noticed Grayjay was a multi-service app, this was something that I was contemplating. You mentioning it almost straight away, off your own back, reinforces it as a necessary step.

Added with https://github.com/duyfken/alternative-front-ends/commit/c22f2cd97f71980a4497cb2d9555a3051a13fa73 (Desktop branch) and https://github.com/duyfken/alternative-front-ends/commit/c3087042fa251111ae5117c08001f4a5a76036dd (Mobile branch).

Links to multi-service apps will only be provided in pre-existing sections (otherwise things will get out of control *very* quickly, due to multi-service apps like Ferdium, which cover hundreds of services).

**Comment by PhilC813** [comment]
> Links to multi-service apps will only be provided in pre-existing sections (otherwise things will get out of control _very_ quickly, due to multi-service apps like Ferdium, which cover hundreds of services).

Fair enough! Stay awesome ~
